/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Book {
    accountingBook?: models.AccountingBook;

    activity?: string;

    attributes?: Array<any>;

    authName?: string;

    baseCurrency?: string;

    businessDate?: models.JDate;

    comment?: string;

    ctccompounding?: boolean;

    ctcconsolidator?: boolean;

    dayChangeRule?: models.DayChangeRule;

    defaultHolidays?: Array<any>;

    eodtime?: number;

    eodtimeDates?: { [key: string]: any; };

    holidays?: Array<string>;

    id?: number;

    key?: any;

    legalEntity?: models.LegalEntity;

    location?: models.TimeZone;

    lockId?: number;

    mutable?: boolean;

    name?: string;

    processingOrgBasedId?: number;

    user?: string;

    valuationTimes?: Array<string>;

    valuationTimezones?: Array<string>;

    version?: number;

}
