/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface CalypsoUserDetails {
    accountNonExpired?: boolean;

    accountNonLocked?: boolean;

    admin?: boolean;

    appName?: string;

    attempts?: number;

    authorities?: Array<models.GrantedAuthority>;

    clientId?: number;

    credentialThresholdInDays?: boolean;

    credentialsExpireUnit?: number;

    credentialsNonExpired?: boolean;

    descriptiveUserName?: string;

    enabled?: boolean;

    fullName?: string;

    hostDetails?: models.InetAddress;

    hostName?: string;

    instanceName?: string;

    lastSuccessfulLoginDatetime?: number;

    password?: string;

    serviceId?: number;

    sessionKey?: string;

    sessionRenewRequired?: boolean;

    tenantId?: string;

    username?: string;

}
