/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface InetAddress {
    address?: Array<string>;

    anyLocalAddress?: boolean;

    canonicalHostName?: string;

    hostAddress?: string;

    hostName?: string;

    linkLocalAddress?: boolean;

    loopbackAddress?: boolean;

    mcglobal?: boolean;

    mclinkLocal?: boolean;

    mcnodeLocal?: boolean;

    mcorgLocal?: boolean;

    mcsiteLocal?: boolean;

    multicastAddress?: boolean;

    siteLocalAddress?: boolean;

}
