/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PSEvent {
    className?: string;

    dataServerName?: string;

    engineName?: string;

    eventStatsUpdated?: boolean;

    eventType?: string;

    id?: number;

    messageHeaders?: any;

    objectId?: number;

    occurrenceTime?: number;

    requiredHeaders?: Array<string>;

    sequence?: number;

    systemData?: any;

    userDetails?: models.CalypsoUserDetails;

}
