/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TradeDto {
    accrual?: number;

    alternateDate?: Date;

    book?: models.BookDto;

    comment?: string;

    counterParty?: models.LegalEntityDto;

    customData?: string;

    enteredDate?: Date;

    enteredUser?: string;

    externalReference?: string;

    id?: number;

    internalReference?: string;

    marketType?: string;

    modifiedUser?: string;

    negociatedPrice?: number;

    negociatedPriceType?: string;

    product?: models.ProductDto;

    quantity?: number;

    role?: string;

    salesPerson?: string;

    settlementCurrency?: string;

    settlementDate?: Date;

    splitBasePrice?: number;

    splitBookPrice?: number;

    splitCurrency?: string;

    status?: string;

    tradeAction?: string;

    tradeCurrency?: string;

    tradeDate?: Date;

    tradePrice?: number;

    trader?: string;

    updatedDate?: Date;

}
