/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface User {
    accessFilterSets?: Array<any>;

    accessReadOnlyFilterSets?: Array<any>;

    accountLockedDatetime?: Date;

    accountLockedReason?: User.AccountLockedReasonEnum;

    books?: Array<any>;

    cryptedPassword?: Array<string>;

    description?: string;

    filterSets?: Array<any>;

    fullName?: string;

    functions?: Array<any>;

    groups?: Array<any>;

    lastPasswordChangeDate?: models.JDate;

    loginIddleDays?: number;

    loginIdleDays?: number;

    maxLoginAttempt?: number;

    maxTradeBundles?: number;

    maxTrades?: number;

    name?: string;

    passwordChangeDue?: boolean;

    passwordCheckDigit?: boolean;

    passwordCheckSpecialChar?: boolean;

    passwordMinLength?: number;

    permissionAttributes?: any;

    poid?: number;

    poids?: Array<number>;

    pricingEnvs?: Array<any>;

    readOnlyBooks?: Array<any>;

    readOnlyPricingEnvs?: Array<any>;

    representingLE?: { [key: string]: Array<any>; };

    staticDataFilters?: Array<any>;

    thresholdDays?: number;

    thresholdIsDays?: boolean;

    thresholdLogins?: number;

    tradeFilters?: Array<any>;

    updateUser?: string;

    version?: number;

}
export namespace User {
    export enum AccountLockedReasonEnum {
        LockedByAdmin = <any> 'Locked by Admin',
        MaxLoginAttemptsExceeded = <any> 'Max login attempts exceeded',
        LoginDelayExceeded = <any> 'Login delay exceeded'
    }
}
